services:
  mysql:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql

  ml:
    build: ./ml
    restart: unless-stopped
    ports:
      - "8001:8001"

  db:
    build: ./db
    restart: unless-stopped
    depends_on:
      - mysql
      - ml
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: ${DB_NAME}
      ML_SERVICE_URL: http://ml:8001
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    ports:
      - "8000:8000"

volumes:
  mysql_data:
